# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NameablePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=100)),
            ],
            bases=('pages.page',),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_page', to='navigation.Category'),
        ),
    ]
