# Generated by Django 2.2.8 on 2020-01-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nameablepage',
            options={'verbose_name': 'Page nommée', 'verbose_name_plural': 'Pages nommées'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterField(
            model_name='nameablepage',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nameablepage',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_page', to='navigation.Category', verbose_name='Catégorie parente'),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.IntegerField(default=1, verbose_name='Type de page'),
        ),
    ]
