image: python:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: ci
  MYSQL_ROOT_PASSWORD: mysql_password_ci

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V  # Print out python version for debugging
  #  - apt-get update -q && apt-get install mysql-client 
  - pip install -r requirements.txt

test:
  script:
    - python manage.py test --settings valerie.settings.ci_test
