# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('nameablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.NameablePage')),
                ('content', models.TextField(null=True)),
                ('position', models.PositiveIntegerField()),
            ],
            bases=('pages.nameablepage',),
        ),
    ]
