# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_img',
            field=models.ImageField(default=None, upload_to='photos'),
            preserve_default=False,
        ),
    ]
