# Generated by Django 2.2.8 on 2020-05-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200112_1500'),
        ('photos_gallery', '0004_auto_20200112_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('nameablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.NameablePage')),
                ('content_Item', models.TextField(null=True)),
                ('position_Item', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('pages.nameablepage',),
        ),
    ]
