# Generated by Django 2.2.8 on 2020-05-03 16:37

from django.db import migrations, models
import django.db.models.deletion

from valerie.photos_gallery.models import PhotoGallery


def copy_photo(apps, schema_editor):
    Photo = apps.get_model('photos_gallery', 'Photo')

    for old_photo in Photo.objects.all():
        new_photo = PhotoGallery()
        new_photo.content_Item = old_photo.content
        new_photo.position_Item = old_photo.position
        new_photo.title = old_photo.title
        new_photo.slug = old_photo.slug
        new_photo.parent_id = old_photo.parent.id
        new_photo.type = old_photo.type
        new_photo.photo_img = old_photo.photo_img
        new_photo.id = old_photo.id
        new_photo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('photos_gallery', '0005_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('galleryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photos_gallery.GalleryItem')),
                ('photo_img', models.ImageField(upload_to='upload/photos')),
            ],
            bases=('photos_gallery.galleryitem',),
        ),
        migrations.RunPython(copy_photo),
    ]
