# Generated by Django 2.2.8 on 2020-05-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_auto_20200112_1500'),
        ('pages', '0002_auto_20200112_1500'),
        ('photos_gallery', '0006_newphoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='OldPhoto',
        ),
    ]
