# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-29 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_auto_20180324_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_mini',
            field=models.ImageField(null=True, upload_to='upload/categorie'),
        ),
    ]
