# Generated by Django 2.2.8 on 2020-01-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_auto_20180929_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='default_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_page', to='pages.Page', verbose_name='Page par défaut'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img_mini',
            field=models.ImageField(null=True, upload_to='upload/categories', verbose_name='Miniature'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_cat', to='navigation.Category', verbose_name='Catégorie parente'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Titre'),
        ),
    ]
