# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='navigation.Category')),
                ('is_home', models.BooleanField(default=False)),
            ],
            bases=('navigation.category',),
        ),
        migrations.RemoveField(
            model_name='category',
            name='default_child',
        ),
        migrations.RemoveField(
            model_name='category',
            name='home',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_cat', to='navigation.ParentCategory'),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='default_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_child_subcat', to='navigation.Category'),
        ),
    ]
