# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='default_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_page', to='navigation.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
