# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0010_auto_20180311_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_page', to='navigation.Category'),
        ),
    ]
