# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('navigation', '0011_auto_20180311_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='default_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_page', to='pages.Page'),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
