# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='youtube_link',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
