# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-20 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_auto_20180909_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(),
        ),
    ]
