# Generated by Django 2.1.11 on 2019-12-27 18:50

from django.db import migrations, models
import django.db.models.deletion

from valerie.press.models import ImageAttachmentArticle


def copy_image_att(apps, schema_editor):
    ImageArticle = apps.get_model('press', 'ImageArticle')

    for old_img in ImageArticle.objects.all():
        new_img = ImageAttachmentArticle()
        new_img.img = old_img.img
        new_img.position = old_img.position
        new_img.article_id = old_img.article.id
        new_img.save()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('press', '0004_auto_20181020_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAttachmentArticle',
            fields=[
                ('imageattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.ImageAttachment')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_attachment_image', to='press.Article')),
            ],
            bases=('common.imageattachment',),
        ),
        migrations.RunPython(copy_image_att),
    ]
