# Generated by Django 2.1.11 on 2019-12-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0005_imageattachmentarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagearticle',
            name='article',
        ),
        migrations.DeleteModel(
            name='ImageArticle',
        ),
    ]
