# Generated by Django 2.1.11 on 2019-12-27 18:50

from django.db import migrations, models
import django.db.models.deletion
import valerie.common.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Attachment')),
                ('doc', models.FileField(upload_to=valerie.common.models.Attachment.upload_path)),
            ],
            bases=('common.attachment',),
        ),
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Attachment')),
                ('img', models.ImageField(upload_to=valerie.common.models.Attachment.upload_path)),
            ],
            bases=('common.attachment',),
        ),
    ]
