# Generated by Django 3.0 on 2019-12-31 10:46

from django.db import migrations, models
import valerie.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='documentattachment',
            name='doc',
            field=models.FileField(upload_to=valerie.common.models.Attachment.upload_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='img',
            field=models.ImageField(upload_to=valerie.common.models.Attachment.upload_path, verbose_name='Image'),
        ),
    ]
