# Generated by Django 2.1.11 on 2019-12-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191225_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageevent',
            old_name='article',
            new_name='event',
        ),
    ]
