# Generated by Django 2.1.11 on 2019-12-26 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191225_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.FileField(upload_to='upload/events')),
                ('position', models.PositiveIntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_document', to='events.Event')),
            ],
        ),
    ]
