# Generated by Django 2.1.11 on 2019-12-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_documentevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentevent',
            old_name='link',
            new_name='doc',
        ),
    ]
