# Generated by Django 2.1.11 on 2019-12-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20191226_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentevent',
            name='title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
