# Generated by Django 2.1.11 on 2019-12-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_documentevent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
