# Generated by Django 3.0 on 2019-12-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20191227_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=256, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(max_length=256, null=True, verbose_name='Lien (facultatif)'),
        ),
    ]
